# This file is a template, and might need editing before it works on your project.
# Explaination on the scripts:
# https://gitlab.com/gitlab-examples/kubernetes-deploy/blob/master/README.md
image: in.thewardro.be:4567/docker/kubernetes-deploy:latest

variables:
  # Application deployment domain
  KUBE_DOMAIN: bible.com

stages:
  - build
  - test
  - review
  - staging
  - production

build:
  stage: build
  script:
    - command build
  only:
    - branches

production:
  stage: production
  variables:
    CI_ENVIRONMENT_URL: http://test-production.$KUBE_DOMAIN
    SECRET_SECURE_HOSTNAME: $CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: production
    url: http://test-production.$KUBE_DOMAIN
  when: manual
  only:
    - master

staging:
  stage: staging
  variables:
    CI_ENVIRONMENT_URL: http://test-staging.$KUBE_DOMAIN
    SECRET_SECURE_HOSTNAME: $CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: staging
    url: http://test-staging.$KUBE_DOMAIN
  only:
    - master

review:
  stage: review
  variables:
    CI_ENVIRONMENT_URL: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    SECRET_SECURE_HOSTNAME: $CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - export SHORT=$(echo review-$CI_COMMIT_SHA | cut -c-14)
    - export REVIEW_MEMCACHE_SERVERS=$SHORT-memcached.bible.svc.cluster.local:11211 
    - command deploy
    - helm list | grep $SHORT || helm install --name $SHORT --set memcached.verbosity=v --set memcached.maxItemMemory=100 stable/memcached --version 0.4.1 --namespace $KUBE_NAMESPACE --replace
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
    - export SHORT=$(echo review-$CI_COMMIT_SHA | cut -c-14)
    - helm delete $SHORT
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
