files:
  - source: /ruby/config/locales/source/en.yml
    translation: /ruby/config/locales/%osx_locale%.yml
    languages_mapping:
      osx_locale:
        'zh-CN': 'zh-CN'
        'es-la': 'es-LA'
        'zh-TW': 'zh-TW'
        'zh-HK': 'zh-HK'
        'en-GB': 'en-GB'
        'pt-PT': 'pt'
        'pt-BR': 'pt-BR'
        'sv-SE': 'sv'