files:
  - source: /ruby/config/locales/en.yml
    translation: /ruby/config/locales/%osx_locale%.yml
    languages_mapping:
      osx_locale:
        es-ES: es-ES
        es-la: es
        zh-CN: zh-CN
        zh-TW: zh-TW
        zh-HK: zh-HK
        en-GB: en-GB
        pt-PT: pt-PT
        pt-BR: pt
        sv-SE: sv
        fil: tl
        ckb-IR: ckb
        myz: my-MM 
  - source: /ruby/config/locales/kids/en.yml
    translation: /ruby/config/locales/kids/%osx_locale%.yml
    languages_mapping:
      osx_locale:
        es-ES: es-ES
        es-la: es
        zh-CN: zh-CN
        zh-TW: zh-TW
        zh-HK: zh-HK
        en-GB: en-GB
        pt-PT: pt-PT
        pt-BR: pt
        sv-SE: sv
        fil: tl
        ckb-IR: ckb
        myz: my-MM
  - source: /ruby/config/locales/privacy_and_terms/en.yml
    translation: /ruby/config/locales/privacy_and_terms/%osx_locale%.yml
    languages_mapping:
      osx_locale:
        es-ES: es-ES
        es-la: es
        zh-CN: zh-CN
        zh-TW: zh-TW
        zh-HK: zh-HK
        en-GB: en-GB
        pt-PT: pt-PT
        pt-BR: pt
        sv-SE: sv
        fil: tl
        ckb-IR: ckb
        myz: my-MM
