files:
  - source: /ruby/config/locales/source/en.yml
    translation: /ruby/config/locales/%osx_locale%.yml
    languages_mapping:
      osx_locale:
        'es-ES': 'es-ES'
        'es-LA': 'es'
        'zh-CN': 'zh-CN'
        'zh-TW': 'zh-TW'
        'zh-HK': 'zh-HK'
        'en-GB': 'en-GB'
        'en': 'en'
        'pt-PT': 'pt-PT'
        'pt-BR': 'pt'
        'sv-SE': 'sv'