common:
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  # yv-development-cb (works for youversion-web.dev)
  #facebook_app_id: 306713076033387
  #facebook_secret: 1a8bf87913629f4162b6c91e5fe943a2
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  avatar_path: https://d5xlnxqvcdji7.cloudfront.net/users/images/
  #note: this direct path will not work for users without avatars (404's)
  #workaround should be coming by EOY 2012
  avatar_path_direct: https://static-youversionapi-com.s3.amazonaws.com/users/images/
  bloodhound_username: lifechurchtv
  bloodhound_password: password
  api_root: youversionapi.com
  api_referer: web-dev.youversionapi.com
  #api_root: youversionapistaging.com
  #api_referer: web-dev.youversionapistaging.com
  api_version: "3.0"
  memcache_server: localhost
  #
  # Timeouts: all times are in seconds
  api_default_timeout: 10
  rack_execution_timeout: 1000
  #
  # Caching: all times are in minutes
  memoization_cache_expiration: 720
  very_short_cache_expiration: 2
  short_cache_expiration: 10
  long_cache_expiration: 45
  very_long_cache_expiration: 720
  rate_limit: 120

staging:
  #api_root: youversionapi.com
  #api_referer: web-staging.youversionapi.com
  api_root: youversionapistaging.com
  api_referer: web-dev-staging.youversionapistaging.com
  api_default_timeout: 5
  rack_execution_timeout: 15

production:
  api_root: youversionapi.com
  api_referer: web.youversionapi.com
  api_default_timeout: 5
  rack_execution_timeout: 15
  memcache_server: memcache.youversion.com
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
