common:
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  avatar_path: http://d5xlnxqvcdji7.cloudfront.net/users/images/
  avatar_path_s3: http://static-youversionapi-com.s3-website-us-east-1.amazonaws.com/users/images/
  ssl_avatar_path: https://d5xlnxqvcdji7.cloudfront.net/users/images/
  ssl_avatar_path_s3: http://static-youversionapi-com.s3-website-us-east-1.amazonaws.com/users/images/
  bloodhound_username: lifechurchtv
  bloodhound_password: password
  api_root: youversionapistaging.com
  api_referer: web-dev.youversionapistaging.com
  api_version: "3.0"
  memcache_server: localhost

staging:
  api_root: youversionapi.com
  api_referer: web-staging.youversionapi.com

production:
  api_root: youversionapi.com
  api_referer: web.youversionapi.com
  memcache_server: memcache.youversion.com
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
