development:
  api_root: https://api.yvdev.com
  api_version: "2.2"
  memcache_server: localhost

test: &test
  api_root: https://api.yvdev.com
  api_version: "2.2"
  memcache_server: localhost

production:

demo: *test