common: &common
  # youversion.com
  # twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  # twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  # facebook_app_id: "105030176203924"
  # facebook_secret: "9d03678ddd8b5588c4e6c91bd996cce2"
  #
  # www.cbailey.yvdev.com
  # twitter_key: "jJwCaFguoe3a40fXBVWsCw"
  # twitter_secret: "Hf7dR18UjU6nuoeVTm15EQSDdR1NmbxlElS3tpFRY"
  # facebook_app_id: "214636785287293"
  # facebook_secret: "279d2af7fd1de6ed8d74a67ca9de530a"
  #
  # yv.chadbailey.net
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  avatar_path: https://s3.amazonaws.com/avatars.youversion.com/
  bloodhound_username: lifechurchtv
  bloodhound_password: password

development:
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  avatar_path: https://s3.amazonaws.com/avatars.youversion.com/
  bloodhound_username: lifechurchtv
  bloodhound_password: password
  api_root: api.youversion.com
  api_referer: web-dev.youversion.com
  api_version: "2.4"
  memcache_server: localhost

test: &test
  <<: *common
  api_root: api.yvdev.com
  api_referer: web-testing.youversion.com
  api_version: "2.4"
  memcache_server: localhost

staging:
  <<: *common
  <<: *test
  api_root: api.youversion.com
  api_referer: web-staging.youversion.com
  memcache_server: memcache.youversion.com
  memcache_server: localhost

production: &production
  <<: *common
  api_root: api.youversion.com
  api_referer: web.youversion.com
  api_version: "2.4"
  memcache_server: memcache.youversion.com
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  # facebook_app_id: "105030176203924"
  # facebook_secret: "9d03678ddd8b5588c4e6c91bd996cce2"
  # facebook_app_id: "306713076033387"
  # facebook_secret: "1a8bf87913629f4162b6c91e5fe943a2"

demo: *test

production_yv:
  <<: *production

production_heroku:
  <<: *production

