# Boilerplate for now. Will fill in when necessary.
common: &common
  adapter: mysql2
  host: localhost
  username: root
  password: "123456789"

development:
  <<: *common
  database: yv_web_development

test:
  <<: *common
  database: yv_web_test

production:
  <<: *common
  database: yv_web_production

cucumber:
  <<: *test