# Boilerplate for now. Will fill in when necessary.
common: &common
  adapter: postgresql
  host: localhost
  port: 5432
  username: yv_web

development:
  <<: *common
  database: yv_web_development

test:
  <<: *common
  database: yv_web_test

production:
  <<: *common
  host: postgres.youversion.com
  port: 6000
  database: yv_web_production

cucumber:
  <<: *test
