# Boilerplate for now. Will fill in when necessary.
common: &common
  adapter: postgresql
  host: localhost
  port: 5432
  username: yv_web
  database: yv_web_production

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *common
  database: yv_web_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *common

production:
  <<: *common
  host: postgres-web.youversion.com
  port: 6000

cucumber:
  <<: *test
