af:
  text: [5, 6, 117, 50, 2, 286, 281, 124, 274, 185, 418, 604]
  audio: []
ar:
  text: [211, 116]
  audio: []
bg:
  text: [23, 190, 901, 196, 22]
  audio: []
ca: []
cs: []
cy: []
da: []
de: []
en:
  text: [1, 111, 116, 59, 12, 97, 100, 72]
  audio: [1, 111, 116, 59]
en-GB: []
es: []
es-ES: []
fa: []
fi: []
fr: []
hi: []
hr: []
hu: []
id: []
it: []
ja: []
km: []
ko: []
lv: []
mk: []
mn: []
ms: []
nl: []
no: []
pl: []
pt: []
pt-PT: []
ro: []
ru: []
sk: []
sq: []
sv: []
sw: []
ta: []
th: []
tl: []
tr: []
uk: []
vi: []
zh-CN: []
zh-TW: []