:versions:
  'kjv': 1
  'abd07-af': 2
  'accnt-acr': 3
  'acunt-acu': 4
  'afr53-af': 5
  'afr83': 6
  'albb': 7
  'amp': 8
  'apsd-ceb': 9
  'apsd-hil': 10
  'arc': 11
  'asv': 12
  'avd-ar': 13
  'avdrv-ar': 14
  'b21': 15
  'bao-bao': 16
  'bbc-bbc': 17
  'bbnt-bth': 18
  'bd2011-vie': 19
  'bdan': 20
  'bds': 21
  'bg1871': 22
  'bg1940': 23
  'bhebnt': 24
  'bhnt': 25
  'bhunnt': 26
  'bimk': 27
  'blph-es': 28
  'bm11-no': 29
  'bm85-no': 30
  'books-eng': 31
  'bsn-sna': 32
  'bsv': 33
  'bts-bts': 34
  'btx-btx': 35
  'ccb': 36
  'ceb': 37
  'cev': 38
  'ckk': 39
  'cnv': 40
  'cnvs': 41
  'cpdv': 42
  'csb': 43
  'csbkr': 44
  'cslav-chu': 45
  'cunp': 46
  'cunpsd-cmn': 47
  'cunpss': 48
  'da1871': 49
  'db': 50
  'delut': 51
  'dhh': 52
  'dhhe-es': 53
  'do885-it': 54
  'dra': 55
  'eab-eu': 56
  'elb': 57
  'elb71': 58
  'esv': 59
  'fi1776': 60
  'finpr': 61
  'fmar': 62
  'frc97-fr': 63
  'frdby': 64
  'gantp': 65
  'gdc-gn': 66
  'gna93-ar': 67
  'gnt': 68
  'gntd': 69
  'gwt': 70
  'hau-ha': 71
  'hcsb': 72
  'hfa': 73
  'hnv': 74
  'htb': 75
  'hwc-hwc': 76
  'igbob-ig': 77
  'igd': 78
  'int-sq': 79
  'itriv': 80
  'ja1955': 81
  'jav-ja': 82
  'jlb': 83
  'kar': 84
  'khsv-km': 85
  'klb': 86
  'kqa': 87
  'krv': 88
  'lbla': 89
  'leb': 90
  'lhbr-lhu': 91
  'lm': 92
  'lsg-fr': 93
  'maor': 94
  'mbcl-bn': 95
  'mg1865': 96
  'msg': 97
  'mtds': 98
  'mtnt-tih': 99
  'nasb': 100
  'nav': 101
  'nb': 102
  'nblh': 103
  'nbs-fr': 104
  'ncv': 105
  'neg79': 106
  'net': 107
  'ngu2011-deu': 108
  'nia-nia': 109
  'nirv-eng': 110
  'niv': 111
  'niv84': 112
  'nivuk': 113
  'nkjv': 114
  'nlbnt': 115
  'nlt': 116
  'nlv': 117
  'nmv-fas': 118
  'nn11-nn': 119
  'nn85-nn': 120
  'norsk': 121
  'nr06-ita': 122
  'nr94': 123
  'nso51-nso': 124
  'ntlh': 125
  'ntr': 126
  'ntv': 127
  'nvi': 128
  'nvi-por': 129
  'ojb': 130
  'ost': 131
  'pbg': 132
  'pdv-fr': 133
  'pnt-pne': 134
  'potl': 135
  'pov-fas': 136
  'psz': 137
  'pubg-pol': 138
  'rcuv': 139
  'rcuvss': 140
  'rdv24-it': 141
  'rnksv': 142
  'rsz': 143
  'rtpv05-tl': 144
  'ruvz': 145
  'rvc': 146
  'rves': 147
  'rvr60': 149
  'rvr60-es': 149
  'rvr95': 150
  'rvv11-vi': 151
  's21': 152
  'sab': 153
  'sb00-sv': 154
  'sbcl-bn': 155
  'sblg': 156
  'sch2000-deu': 157
  'sch51': 158
  'sda-sda': 159
  'sfb': 160
  'sk73': 161
  'snc': 162
  'ssv': 163
  'suv-sw': 164
  'sv1750': 165
  'sven': 166
  'syno-ru': 167
  'tb': 168
  'tb-por': 169
  'tcl02-tr': 170
  'tdir-iba': 171
  'tdvr-dtp': 172
  'tgv-grc': 173
  'thsv': 174
  'tkjv': 175
  'tla': 176
  'tlab': 177
  'tlad': 178
  'tncv-tha': 179
  'tniv': 180
  'tpv-fa': 181
  'tr1624': 182
  'tr1894': 183
  'tso89-ts': 184
  'tsw70-tn': 185
  'ubio': 186
  'ugv': 187
  'ukrk': 188
  'urd-ur': 189
  'vbg': 190
  'vdc': 191
  'vdcc': 192
  'vi1934': 193
  'wa53': 194
  'wbar': 195
  'wbbg': 196
  'wbes': 197
  'wbhu': 198
  'wbid': 199
  'wbpt': 200
  'wbru': 201
  'wbsr': 202
  'wbth': 203
  'wbuk': 204
  'wbvi': 205
  'web': 206
  'yce-yo': 207
  'ziv': 208
  'ntpt-grcll': 209
  'blp-eses': 210
  'ntlh-pt': 211
  'arc_1-pt': 212
  'cbunt-cbu': 213
  'bti-eses': 214
  'arc-ptpt': 215
  'ckint-cki': 216
  'clent-cle': 217
  'chipbo-cap': 218
  'cpant-cpa': 219
  'iumith-ium': 220
  'bcn-cy': 221
  'bhti-es': 222
  'eabd-eu': 223
  'gyob0253-gyr': 224
  'nhent-nhe': 225
  'piont-pio': 226
  'point-poi': 227
  'bpt-ptpt': 228
  'amunt-amu': 229
  'aucnt-auc': 230
  'baont-bao': 231
  'iuminor-ium': 232
  'iuminr-ium': 233
  'bzdnt-bzd': 234
  'caont-cao': 235
  'capnt-cap': 236
  'carnt-car': 237
  'cpunt-cpu': 238
  'crnnt-crn': 239
  'cuknt-cuk': 240
  'huvnt-huv': 241
  'diknt-dik': 242
  'djknt-djk': 243
  'djnt-djr': 244
  'igb-ign': 245
  'iumilao-ium': 246
  'ixlnt-ixl': 247
  'jav-jav': 248
  'jicnt-jic': 249
  'jvnnt-jvn': 250
  'kntp-kmr': 251
  'lifnt-lif': 252
  'mbov-lus': 253
  'mksnt-mks': 254
  'nkont-nko': 255
  'nso00-nso': 256
  'oodnt-ood': 257
  'otent-ote': 258
  'otqnt-otq': 259
  'padnt-pad': 260
  'qca04-qxr': 261
  'qchi04-qug': 262
  'qnbnt-quh': 263
  'quii-qvi': 264
  'qvmnt-qvm': 265
  'qvsnt-qvs': 266
  'qvwnt-qvw': 267
  'qxnnt-qxn': 268
  'rus-brus-ru': 269
  'sjant-sja': 270
  'snnnt-snn': 271
  'srmnt-srm': 272
  'sso61so-st': 273
  'sso89so-st': 274
  'th1971-th': 275
  'tosnt-tos': 276
  'tb10-pt': 277
  'tsw08no-tn': 278
  'tzznt-tzo': 279
  'ven98-ve': 280
  'xho75-xh': 281
  'xho96-xh': 282
  'zabnt-zab': 283
  'zarnt-zar': 284
  'sumu-sum': 285
  'zul59-zu': 286
  'wmb-cy': 287
  'tblnt-tbl': 288
  'tcant-tca': 289
  'qxont-qxo': 290
  'zpont-zpo': 291
  'alnt-sq': 292
  'ayop-ayr': 293
  'cevuk-en': 294
  'deu-bdeu-de': 295
  'gntuk-en': 296
  'ita-bita-it': 297
  'msktu-miq': 298
  'ngbm-nnh': 299
  'pol-bpol-pol': 300
  'rnt-rim': 301
  'ban-ban': 302
  'cev-en': 303
  'esknt-esk': 304
  'rnksv-ko': 305
  'tb-id': 306
:books:
  'Gen': 'GEN'
  'Exod': 'EXO'
  'Lev': 'LEV'
  'Num': 'NUM'
  'Deut': 'DEU'
  'Josh': 'JOS'
  'Judg': 'JDG'
  'Ruth': 'RUT'
  '1Sam': '1SA'
  '2Sam': '2SA'
  '1Kgs': '1KI'
  '2Kgs': '2KI'
  '1Chr': '1CH'
  '2Chr': '2CH'
  'Ezra': 'EZR'
  'Neh': 'NEH'
  'Esth': 'EST'
  'Job': 'JOB'
  'Ps': 'PSA'
  'Prov': 'PRO'
  'Eccl': 'ECC'
  'Song': 'SNG'
  'Isa': 'ISA'
  'Jer': 'JER'
  'Lam': 'LAM'
  'Ezek': 'EZK'
  'Dan': 'DAN'
  'Hos': 'HOS'
  'Joel': 'JOL'
  'Amos': 'AMO'
  'Obad': 'OBA'
  'Jonah': 'JON'
  'Mic': 'MIC'
  'Nah': 'NAM'
  'Hab': 'HAB'
  'Zeph': 'ZEP'
  'Hag': 'HAG'
  'Zech': 'ZEC'
  'Mal': 'MAL'
  'Matt': 'MAT'
  'Mark': 'MRK'
  'Luke': 'LUK'
  'John': 'JHN'
  'Acts': 'ACT'
  'Rom': 'ROM'
  '1Cor': '1CO'
  '2Cor': '2CO'
  'Gal': 'GAL'
  'Eph': 'EPH'
  'Phil': 'PHP'
  'Col': 'COL'
  '1Thess': '1TH'
  '2Thess': '2TH'
  '1Tim': '1TI'
  '2Tim': '2TI'
  'Titus': 'TIT'
  'Phlm': 'PHM'
  'Heb': 'HEB'
  'Jas': 'JAS'
  '1Pet': '1PE'
  '2Pet': '2PE'
  '1John': '1JN'
  '2John': '2JN'
  '3John': '3JN'
  'Jude': 'JUD'
  'Rev': 'REV'
  'Tob': 'TOB'
  'Jdt': 'JDT'
  'AddEsth': 'ESG'
  'Wis': 'WIS'
  'Sir': 'SIR'
  'Bar': 'BAR'
  'EpJer': 'LJE'
  'PrAzar': 'S3Y'
  'Sus': 'SUS'
  'Bel': 'BEL'
  '1Macc': '1MA'
  '2Macc': '2MA'
  '3Macc': '3MA'
  '4Macc': '4MA'
  '1Esd': '1ES'
  '2Esd': '2ES'
  'PrMan': 'MAN'
  'Ps151': 'PS2'
  'Odes': 'ODA'
  'PssSol': 'PSS'
  '4Esd': 'EZA'
  '2Bar': '2BA'
  'EpBar': 'LBA'
  'Jub': 'JUB'
  '1En': 'ENO'
  '4Bar': '4BA'
  'EpLao': 'LAO'
  'Lkac': 'LKA'
  'gen': 'GEN'
  'exod': 'EXO'
  'lev': 'LEV'
  'num': 'NUM'
  'deut': 'DEU'
  'josh': 'JOS'
  'judg': 'JDG'
  'ruth': 'RUT'
  '1sam': '1SA'
  '2sam': '2SA'
  '1kgs': '1KI'
  '2kgs': '2KI'
  '1chr': '1CH'
  '2chr': '2CH'
  'ezra': 'EZR'
  'neh': 'NEH'
  'esth': 'EST'
  'job': 'JOB'
  'ps': 'PSA'
  'prov': 'PRO'
  'eccl': 'ECC'
  'song': 'SNG'
  'isa': 'ISA'
  'jer': 'JER'
  'lam': 'LAM'
  'ezek': 'EZK'
  'dan': 'DAN'
  'hos': 'HOS'
  'joel': 'JOL'
  'amos': 'AMO'
  'obad': 'OBA'
  'jonah': 'JON'
  'mic': 'MIC'
  'nah': 'NAM'
  'hab': 'HAB'
  'zeph': 'ZEP'
  'hag': 'HAG'
  'zech': 'ZEC'
  'mal': 'MAL'
  'matt': 'MAT'
  'mark': 'MRK'
  'luke': 'LUK'
  'john': 'JHN'
  'acts': 'ACT'
  'rom': 'ROM'
  '1cor': '1CO'
  '2cor': '2CO'
  'gal': 'GAL'
  'eph': 'EPH'
  'phil': 'PHP'
  'col': 'COL'
  '1thess': '1TH'
  '2thess': '2TH'
  '1tim': '1TI'
  '2tim': '2TI'
  'titus': 'TIT'
  'phlm': 'PHM'
  'heb': 'HEB'
  'jas': 'JAS'
  '1pet': '1PE'
  '2pet': '2PE'
  '1john': '1JN'
  '2john': '2JN'
  '3john': '3JN'
  'jude': 'JUD'
  'rev': 'REV'
  'tob': 'TOB'
  'jdt': 'JDT'
  'addesth': 'ESG'
  'wis': 'WIS'
  'sir': 'SIR'
  'bar': 'BAR'
  'epjer': 'LJE'
  'prazar': 'S3Y'
  'sus': 'SUS'
  'bel': 'BEL'
  '1macc': '1MA'
  '2macc': '2MA'
  '3macc': '3MA'
  '4macc': '4MA'
  '1esd': '1ES'
  '2esd': '2ES'
  'prman': 'MAN'
  'ps151': 'PS2'
  'odes': 'ODA'
  'psssol': 'PSS'
  '4esd': 'EZA'
  '2bar': '2BA'
  'epbar': 'LBA'
  'jub': 'JUB'
  '1en': 'ENO'
  '4bar': '4BA'
  'eplao': 'LAO'
  'lkac': 'LKA'