apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_JOB_ID"
spec:
  minAvailable: 85%
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
