---
# tasks file for nodejs

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  tags:
    - nodejs

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes
  tags:
    - nodejs

- name: Add NodeSource repository preferences
  template:
    src: deb_nodesource_com_node.pref.j2
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref
  tags:
    - nodejs

- name: Install Node.js
  apt:
    name: nodejs={{ nodejs_version }}*
    state: installed
  tags:
    - nodejs