aa: "Afar (afar)"
ab: "Abkhazian (abkhaze)"
af: "Afrikaans (afrikaans)"
ak: "Akan (akan)"
sq: "Albanian (albanais)"
am: "Amharic (amharique)"
ar: "Arabic (arabe)"
an: "Aragonese (aragonais)"
hy: "Armenian (arménien)"
as: "Assamese (assamais)"
av: "Avaric (avar)"
ae: "Avestan (avestique)"
ay: "Aymara (aymara)"
az: "Azerbaijani (azéri)"
ba: "Bashkir (bachkir)"
bm: "Bambara (bambara)"
eu: "Basque (basque)"
be: "Belarusian (biélorusse)"
bn: "Bengali (bengali)"
bh: "Bihari languages (langues biharis)"
bi: "Bislama (bichlamar)"
bs: "Bosnian (bosniaque)"
br: "Breton (breton)"
bg: "Bulgarian (bulgare)"
my: "Burmese (birman)"
ca: "Catalan; Valencian (catalan; valencien)"
ch: "Chamorro (chamorro)"
ce: "Chechen (tchétchène)"
zh: "Chinese (chinois)"
cu: "Church Slavic (slavon d'église)"
cv: "Chuvash (tchouvache)"
kw: "Cornish (cornique)"
co: "Corsican (corse)"
cr: "Cree (cree)"
cs: "Czech (tchèque)"
da: "Danish (danois)"
dv: "Divehi; Dhivehi; Maldivian (maldivien)"
nl: "Dutch; Flemish (néerlandais; flamand)"
dz: "Dzongkha (dzongkha)"
en: "English (anglais)"
eo: "Esperanto (espéranto)"
et: "Estonian (estonien)"
ee: "Ewe (éwé)"
fo: "Faroese (féroïen)"
fj: "Fijian (fidjien)"
fi: "Finnish (finnois)"
fr: "French (français)"
fy: "Western Frisian (frison occidental)"
ff: "Fulah (peul)"
ka: "Georgian (géorgien)"
de: "German (allemand)"
gd: "Gaelic; Scottish Gaelic (gaélique; gaélique écossais)"
ga: "Irish (irlandais)"
gl: "Galician (galicien)"
gv: "Manx (manx; mannois)"
el: "Greek, Modern (1453-) (grec moderne (après 1453))"
gn: "Guarani (guarani)"
gu: "Gujarati (goudjrati)"
ht: "Haitian; Haitian Creole (haïtien; créole haïtien)"
ha: "Hausa (haoussa)"
he: "Hebrew (hébreu)"
hz: "Herero (herero)"
hi: "Hindi (hindi)"
ho: "Hiri Motu (hiri motu)"
hr: "Croatian (croate)"
hu: "Hungarian (hongrois)"
ig: "Igbo (igbo)"
is: "Icelandic (islandais)"
io: "Ido (ido)"
ii: "Sichuan Yi; Nuosu (yi de Sichuan)"
iu: "Inuktitut (inuktitut)"
id: "Indonesian (indonésien)"
ik: "Inupiaq (inupiaq)"
it: "Italian (italien)"
jv: "Javanese (javanais)"
ja: "Japanese (japonais)"
kl: "Kalaallisut; Greenlandic (groenlandais)"
kn: "Kannada (kannada)"
ks: "Kashmiri (kashmiri)"
kr: "Kanuri (kanouri)"
kk: "Kazakh (kazakh)"
km: "Central Khmer (khmer central)"
ki: "Kikuyu; Gikuyu (kikuyu)"
rw: "Kinyarwanda (rwanda)"
ky: "Kirghiz; Kyrgyz (kirghiz)"
kv: "Komi (kom)"
kg: "Kongo (kongo)"
ko: "Korean (coréen)"
kj: "Kuanyama; Kwanyama (kuanyama; kwanyama)"
ku: "Kurdish (kurde)"
lo: "Lao (lao)"
la: "Latin (latin)"
lv: "Latvian (letton)"
li: "Limburgan; Limburger; Limburgish (limbourgeois)"
ln: "Lingala (lingala)"
lt: "Lithuanian (lituanien)"
lb: "Luxembourgish; Letzeburgesch (luxembourgeois)"
lu: "Luba-Katanga (luba-katanga)"
lg: "Ganda (ganda)"
mk: "Macedonian (macédonien)"
mh: "Marshallese (marshall)"
ml: "Malayalam (malayalam)"
mi: "Maori (maori)"
mr: "Marathi (marathe)"
ms: "Malay (malais)"
mg: "Malagasy (malgache)"
mt: "Maltese (maltais)"
mn: "Mongolian (mongol)"
na: "Nauru (nauruan)"
nv: "Navajo; Navaho (navaho)"
nr: "Ndebele, South; South Ndebele (ndébélé du Sud)"
nd: "Ndebele, North; North Ndebele (ndébélé du Nord)"
ng: "Ndonga (ndonga)"
ne: "Nepali (népalais)"
nn: "Norwegian Nynorsk (norvégien nynorsk)"
nb: "Bokmål, Norwegian; Norwegian Bokmål (norvégien bokmål)"
"no": "Norwegian (norvégien)"
ny: "Chichewa; Chewa; Nyanja (chichewa; chewa; nyanja)"
oj: "Ojibwa (ojibwa)"
or: "Oriya (oriya)"
om: "Oromo (galla)"
os: "Ossetian; Ossetic (ossète)"
pa: "Panjabi; Punjabi (pendjabi)"
fa: "Persian (persan)"
pi: "Pali (pali)"
pl: "Polish (polonais)"
pt: "Portuguese (portugais)"
ps: "Pushto; Pashto (pachto)"
qu: "Quechua (quechua)"
rm: "Romansh (romanche)"
ro: "Romanian; Moldavian; Moldovan (roumain; moldave)"
rn: "Rundi (rundi)"
ru: "Russian (russe)"
sg: "Sango (sango)"
sa: "Sanskrit (sanskrit)"
si: "Sinhala; Sinhalese (singhalais)"
sk: "Slovak (slovaque)"
sl: "Slovenian (slovène)"
se: "Northern Sami (sami du Nord)"
sm: "Samoan (samoan)"
sn: "Shona (shona)"
sd: "Sindhi (sindhi)"
so: "Somali (somali)"
st: "Sotho, Southern (sotho du Sud)"
es: "Spanish; Castilian (espagnol; castillan)"
sc: "Sardinian (sarde)"
sr: "Serbian (serbe)"
ss: "Swati (swati)"
su: "Sundanese (soundanais)"
sw: "Swahili (swahili)"
sv: "Swedish (suédois)"
ty: "Tahitian (tahitien)"
ta: "Tamil (tamoul)"
tt: "Tatar (tatar)"
te: "Telugu (télougou)"
tg: "Tajik (tadjik)"
tl: "Tagalog (tagalog)"
th: "Thai (thaï)"
bo: "Tibetan (tibétain)"
ti: "Tigrinya (tigrigna)"
to: "Tonga (Tonga Islands) (tongan (Îles Tonga))"
tn: "Tswana (tswana)"
ts: "Tsonga (tsonga)"
tk: "Turkmen (turkmène)"
tr: "Turkish (turc)"
tw: "Twi (twi)"
ug: "Uighur; Uyghur (ouïgour)"
uk: "Ukrainian (ukrainien)"
ur: "Urdu (ourdou)"
uz: "Uzbek (ouszbek)"
ve: "Venda (venda)"
vi: "Vietnamese (vietnamien)"
vo: "Volapük (volapük)"
cy: "Welsh (gallois)"
wa: "Walloon (wallon)"
wo: "Wolof (wolof)"
xh: "Xhosa (xhosa)"
yi: "Yiddish (yiddish)"
yo: "Yoruba (yoruba)"
za: "Zhuang; Chuang (zhuang; chuang)"
zu: "Zulu (zoulou)"
