---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_JOB_ID"
    space: $KUBE_NAMESPACE
    track: stable
spec:
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: $CI_ENVIRONMENT_SLUG
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: $CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        space: $KUBE_NAMESPACE
        track: stable
      annotations:
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - $CI_ENVIRONMENT_SLUG
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: $KUBE_NAMESPACE-$CI_ENVIRONMENT_SLUG
          image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: $PORT
          resources:
            limits:
              cpu: "2"
              memory: "3000Mi"
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
