---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_JOB_ID"
    space: $KUBE_NAMESPACE
    track: stable
spec:
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: $CI_ENVIRONMENT_SLUG
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: $CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        space: $KUBE_NAMESPACE
        track: stable
      annotations:
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - $CI_ENVIRONMENT_SLUG
                topologyKey: "kubernetes.io/hostname"
      hostAliases:
        - ip: 172.22.0.29
          hostnames:
            - nodejs.bible.com
            - events.bible.com
        - ip: 35.226.43.81
          hostnames:
            - localization.youversionapi.com
            - share.youversionapi.com
            - badges.youversionapi.com
            - commq.youversionapi.com
            - jobs.youversionapi.com
            - events.youversionapi.com
            - friends.youversionapi.com
            - friendships.youversionapi.com
            - images.youversionapi.com
            - notifications.youversionapi.com
            - reading-plans.youversionapi.com
            - search.youversionapi.com
            - streaks.youversionapi.com
            - themes.youversionapi.com
            - users.youversionapi.com
            - videos.youversionapi.com
            - licenses.youversionapi.com
            - plans.youversionapi.com
            - movies.youversionapi.com
            - home.youversionapi.com
            - users-service.youversionapi.com
            - app-themes.youversionapi.com
            - developers.youversionapi.com
            - bafk.youversionapi.com
            - lens.youversionapi.com
            - socialmedia.youversionapi.com
      dnsConfig:
        options:
          - name: ndots
            value: "2"
          - name: single-request-reopen
      containers:
        - name: $KUBE_NAMESPACE-$CI_ENVIRONMENT_SLUG
          image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: $PORT
          resources:
            limits:
              cpu: "2"
              memory: "3000Mi"
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 10
            successThreshold: 1
          env:
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
