---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_JOB_ID"
spec:
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: $CI_ENVIRONMENT_SLUG
      space: $KUBE_NAMESPACE
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: $CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        space: $KUBE_NAMESPACE
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: $KUBE_NAMESPACE-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: $PORT
        resources:
          limits:
            cpu: "4"
        readinessProbe:
          httpGet:
            path: /ping_all
            port: 80
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 10
        env:
          - name: YOUVERSION_TOKEN_PHRASE
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: YOUVERSION_TOKEN_PHRASE
          - name: TREADSTONE_SECRET
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: TREADSTONE_SECRET
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: NEW_RELIC_LICENSE_KEY
          - name: NEW_RELIC_APP_NAME
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: NEW_RELIC_APP_NAME
          - name: NEW_RELIC_LOG_LEVEL
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: NEW_RELIC_LOG_LEVEL
          - name: PASSENGER_APP_ENV
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: PASSENGER_APP_ENV
          - name: MEMCACHE_SERVERS
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: MEMCACHE_SERVERS
          - name: HTTP_TIMEOUT
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: HTTP_TIMEOUT
          - name: LOG_LEVEL
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: LOG_LEVEL
          - name: SECURE_TRAFFIC
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: SECURE_TRAFFIC
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: OAUTH_CLIENT_ID
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: OAUTH_CLIENT_SECRET
          - name: SECURE_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: SECURE_HOSTNAME
          - name: YIR_SHA1_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: $KUBE_NAMESPACE-secrets-$STAGE
                key: YIR_SHA1_SECRET_KEY
      imagePullSecrets:
        - name: gitlab-registry
