---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: nodejs-$CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_JOB_ID"
    space: $KUBE_NAMESPACE
    track: stable
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nodejs-$CI_ENVIRONMENT_SLUG
      name: nodejs-$CI_ENVIRONMENT_SLUG
      track: stable
  template:
    metadata:
      labels:
        name: nodejs-$CI_ENVIRONMENT_SLUG
        app: nodejs-$CI_ENVIRONMENT_SLUG
        track: stable
      annotations:
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 30
      hostAliases:
        - ip: 35.226.43.81
          hostnames:
            - localization.youversionapi.com
            - share.youversionapi.com
            - badges.youversionapi.com
            - commq.youversionapi.com
            - jobs.youversionapi.com
            - events.youversionapi.com
            - friends.youversionapi.com
            - friendships.youversionapi.com
            - images.youversionapi.com
            - notifications.youversionapi.com
            - reading-plans.youversionapi.com
            - search.youversionapi.com
            - streaks.youversionapi.com
            - themes.youversionapi.com
            - users.youversionapi.com
            - videos.youversionapi.com
            - licenses.youversionapi.com
            - plans.youversionapi.com
            - movies.youversionapi.com
            - home.youversionapi.com
            - users-service.youversionapi.com
            - app-themes.youversionapi.com
            - developers.youversionapi.com
            - bafk.youversionapi.com
            - lens.youversionapi.com
            - socialmedia.youversionapi.com
      dnsConfig:
        options:
          - name: ndots
            value: "2"
          - name: single-request-reopen
      containers:
        - name: $KUBE_NAMESPACE-nodejs-$CI_ENVIRONMENT_SLUG
          image: $CI_REGISTRY_IMAGE:nodejs-$CI_COMMIT_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["bash", "-c", "sleep 20"]
          resources:
            limits:
              cpu: "1"
              memory: "2000Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
